url: https://ningsuhen.github.io
baseurl:

# Site settings
title: ningsuhen.github.io
email: ningsuhen@waikhom.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ningsuhen Waikhom
  pic: Ningsuhen Waikhom Gravatar.png
  position: Developer
  social:
    - title: twitter
      url: https://twitter.com/ningsuhen
    - title: facebook
      url: https://www.facebook.com/ningsuhen
    - title: stack-overflow
      url: http://stackoverflow.com/users/3478034/nwk
    - title: download
      url: files/ningsuhenwaikhom-resume.pdf
    - title: wordpress
      url: http://waikhom.me


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ningsuhen
  - title: twitter
    url: https://twitter.com/ningsuhen
  - title: facebook
    url: https://www.facebook.com/ningsuhen
  - title: google-plus
    url: https://plus.google.com/+WaikhomNingsuhen
  - title: stack-overflow
    url: http://stackoverflow.com/users/3478034/nwk
#  - title: bitbucket
#    url: http://bitbucket.org/ningsuhen
  - title: github
    url: http://github.com/ningsuhen
  - title: download
    url: files/ningsuhenwaikhom-resume.pdf
  - title: wordpress
    url: http://waikhom.me
  - title: youtube
    url: https://www.youtube.com/user/ningsuhen

# Postal address (add as many lines as necessary)
address:
  - line: B-21, First Floor
  - line: Sector 39, Noida
  - line: Uttar Pradesh, India - 201301

phone: +919899386296


# Build settings
markdown: kramdown
permalink: pretty


asset_bundler:
  compress:
    js: yui
    css: yui
  base_path: /bundles/
  server_url:
  remove_bundled: false
  dev: false
  bundle_name: false
  markup_templates:
    js: "<script type='text/javascript' async src='{{url}}'></script>\n"
    css: "<noscript><link type='text/css' media='all' href='{{url}}' rel='stylesheet' /></noscript><script>function lCss(url,media) {var d=document;var l=d.createElement('link');l.rel='stylesheet';l.type='text/css';l.href=url;l.media=media; d.getElementsByTagName('head')[0].appendChild(l);}function deferredCSS() {lCss('{{url}}','all');}if(window.addEventListener){window.addEventListener('DOMContentLoaded',deferredCSS,false);}else{window.onload = deferredCSS;}</script>"

assets:
  compress:
    css:  sass
    js:   uglifier

skills:
  programming:
    - name: Nodejs
      value: 90
    - name: Python
      value: 80
    - name: PHP
      value: 80
    - name: Javascript
      value: 90
    - name: HTML/CSS
      value: 90
    - name: Java
      value: 60
    - name: Ruby
      value: 30
    - name: Objective-C
      value: 40
    - name: Swift
      value: 60
    - name: Bash/Shell
      value: 60
    - name: MySQL
      value: 80
    - name: MongoDB
      value: 70
  others:
    - name: Photoshop
      value: 70
    - name: Illustrator
      value: 40
    - name: Unity
      value: 30
    - name: Blender
      value: 30
    - name: Linux
      value: 80
    - name: AWS
      value: 60
    - name: Apache/Nginx
      value: 80
    - name: Jenkins
      value: 90
    - name: Adobe CQ5
      value: 50
    - name: Chef
      value: 70
    - name: Capistrano
      value: 50




